################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  #
  #
  dashboard: true
  insecure: true
################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    exposedByDefault: false
    swarmMode: true
    watch: true
################################################################
# Traefik Logging
################################################################
log:
  level: DEBUG
  filePath: "./app/traefik/log/traefik.log"
################################################################
# Entrypoint
################################################################
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  mysql:
    address: ":3306"